sudo: false
language: node_js
node_js:
- 4.2.4
script:
- npm install -g bower && npm install -g vulcanize && bower install && ./build.sh
- cd gem && ./bin/setup && bundle exec rake
deploy:
  provider: rubygems
  skip_cleanup: true
  api_key:
    secure: "ZoDEyGAwPughEEcTOExT1L/1x/7qaBAlKVjQqydRwX3BHDigSWvpjsLpt/308gE9QQ555Tyqyzwjeu8UFZcsopVzeIl5k28bG0+Hs723FyUqhtoyxau2ZNla/bJpl3p1ZKiqzsbizFsWiSmAOREGKBJBrUojt+zj8g6EY4ulc01Rccty9tm4ucTzBi275VWKZq1Mh4rdhdKQW/orWI+U1311yxQEpRFxQ0DneLf3MI//khnGNoLK/55tj2FfUGmajPXRbEA6AMRWn0FKZBsoeuHjbC7TTYbDxSaQvhLE8FZ8HtAW4YApqGq+x+JBsenBJstE4gS/PCnwYASjBXU1wUoTz/EjXaw8SFRhk+4avz1kBTXLnDudTUIWP0OUHOOfhRFFVlLAtcNJH7i8i0F6syrcdGYYdfsESs0ZORYYUu1w8SPEdVG4+7bL5Noc6Mygbxj4tumCv5Yze8ol2dzpMLGv8yqKEYKk6acIWO9RK813NI7/k93qpqmK+HFWBUrKIhWDit13DNwmiKaYNSahfU1P+gclroh/hbz6YYCIV9sPrDEB97dY4pprH6D0+/a7Q0FDr/Rc9dUGqM5UJZQ4gxyGnUYjY59AtZI1j7wsUcbfwHt/tzxNKinqpLs/WHv4+F2j+RjeeHpjQxBbpQZcnTZ2sC6OrdY0x3ormaJNpGs="
  gem: gobstones-blockly
  on:
    tags: true
    repo: Program-AR/gs-element-blockly
